OMDBProject/OMDBProject/Models/DataAccessLayer/IIMDBRepository.cs
using Microsoft.AspNetCore.Mvc;

namespace OMDBProject.Models.DataAccessLayer
{
    public interface IIMDBRepository
    {
        Task<IMDBResponse> SearchMovieResult(string searchTerm);
    }
}

OMDBProject/OMDBProject/Models/DataAccessLayer/IMDBRepository.cs
using Microsoft.AspNetCore.Mvc;
using OMDBProject.Models.DataAccessLayer;

namespace OMDBProject.Models
{
    public class IMDBRepository : IIMDBRepository

    {
        public async Task<IMDBResponse> SearchMovieResult(string searchTerm)
        {
            HttpClient client = new HttpClient();

            client.BaseAddress = new Uri("http://www.omdbapi.com");

            var response = await client.GetFromJsonAsync<IMDBResponse>("?t=" + searchTerm + "&apiKey=aa5bb7ad");

            return response;
        }
    }
}

OMDBProject/OMDBProject/Models/ErrorViewModel.cs
namespace OMDBProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OMDBProject/OMDBProject/Models/IMDBResponse.cs
namespace OMDBProject.Models
{
    public class IMDBResponse
    {
        public string Title { get; set; }
        public string Year { get; set; }
        public string Rated { get; set; }
        public string Released { get; set; }
        public string Runtime { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public string Writer { get; set; }
        public string Actors { get; set; }
        public string Plot { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public string Awards { get; set; }
        public string Poster { get; set; }
        public List<Rating> Ratings { get; set; }
        public string Metascore { get; set; }
        public string imdbRating { get; set; }
        public string imdbVotes { get; set; }
        public string imdbID { get; set; }
        public string Type { get; set; }
        public string DVD { get; set; }
        public string BoxOffice { get; set; }
        public string Production { get; set; }
        public string Website { get; set; }
        public string Response { get; set; }
    }
}

OMDBProject/OMDBProject/Models/MovieNight.cs
namespace OMDBProject.Models
{
    public class MovieNight
    {
        public string Movie1 { get; set; }
        public string Movie2 { get; set; }
        public string Movie3 { get; set; }

    }
}

OMDBProject/OMDBProject/Models/MovieSearch.cs
using System.ComponentModel.DataAnnotations;

namespace OMDBProject.Models
{
    public class MovieSearch
    {
        [Required]
        public string Title { get; set; }
    }
}

OMDBProject/OMDBProject/Models/Rating.cs
namespace OMDBProject.Models
{
    public class Rating
    {
        public string Source { get; set; }
        public string Value { get; set; }
    }
}

OMDBProject/OMDBProject/Models/SearchMovie.cs
using System.ComponentModel.DataAnnotations;

namespace OMDBProject.Models
{
    public class SearchMovie
    {
        [Required]
        public string Title { get; set; }
    }
}

OMDBProject/OMDBProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OMDBProject.Models;
using System.Diagnostics;

namespace OMDBProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OMDBProject/OMDBProject/Controllers/IMDBController.cs
using Microsoft.AspNetCore.Mvc;
using OMDBProject.Models;
using OMDBProject.Models.DataAccessLayer;
using System.Net.Http.Json;

namespace OMDBProject.Controllers
{
    public class IMDBController : Controller
    {
        private readonly IIMDBRepository _iMDBRepository;

        public IMDBController(IIMDBRepository iMDBRepository)
        {
            _iMDBRepository = iMDBRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> MovieSearch(MovieSearch movie)
        {
            IMDBResponse movieResponse = await _iMDBRepository.SearchMovieResult(movie.Title);

            return RedirectToAction("MovieSearchResult", movieResponse);
        }

        public async Task<IActionResult> MovieSearch()
        {
            return View();
        }

        public async Task<IActionResult> MovieSearchResult(IMDBResponse movie)
        {
            return View(movie);
        }

        public IActionResult MovieNight()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> MovieNightResult(MovieNight movies)
        {
            List<IMDBResponse> movieList = new List<IMDBResponse>();

            movieList.Add(await _iMDBRepository.SearchMovieResult(movies.Movie1));
            movieList.Add(await _iMDBRepository.SearchMovieResult(movies.Movie2));
            movieList.Add(await _iMDBRepository.SearchMovieResult(movies.Movie3));

            return View(movieList);

        }

        

        
    }
}

OMDBProject/OMDBProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OMDBProject/OMDBProject/Views/IMDB/MovieNight.cshtml
@model MovieNight

@{
}

<p>
    <form asp-action="MovieNightResult">
        <div>
            <label asp-for="Movie1" class="control-label"></label>
        <input asp-for="Movie1" class="form-control" />
        </div>
        <div>
            <label asp-for="Movie2" class="control-label"></label>
        <input asp-for="Movie2" class="form-control" />
        </div>
        <div>
            <label asp-for="Movie3" class="control-label"></label>
        <input asp-for="Movie3" class="form-control" />
        </div>
        <button class="btn btn-primary" type="submit">Submit</button>

        
    </form>
</p>

OMDBProject/OMDBProject/Views/IMDB/MovieNightResult.cshtml
@model List<IMDBResponse>

<div class="container">
  <div class="row">
      @foreach(IMDBResponse r in Model)
      {
        <div class="col-4">
            <div style="background-color:#212529"class="card" style="width: 18rem;">
                <img src="@r.Poster" class="card-img-top" alt="This is where the poster would be if things hadn't broken.">
                <div class="card-body">
                    <p style = "color:#f5c518" class="card-text">@r.Plot</p>
                </div>
            </div>
        </div>
      }
    
    
    </div>
</div>

OMDBProject/OMDBProject/Views/IMDB/MovieSearch.cshtml
@model SearchMovie

@{
}

<p>
    <form asp-action="Search">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
    </form>
    <button class="btn btn-primary" type="submit">Submit</button>
</p>

OMDBProject/OMDBProject/Views/IMDB/MovieSearchResult.cshtml
@model IMDBResponse



<<div class="container">
  <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <div style="background-color:#212529"class="card" style="width: 18rem;">
                <img src="@Model.Poster" class="card-img-top" alt="This is where the poster would be if things hadn't broken.">
                <div class="card-body">
                    <p style = "color:#f5c518" class="card-text">@Model.Plot</p>
                </div>
            </div>
        </div>
        <div class="col-4"></div>
    
    
    </div>
</div>

OMDBProject/OMDBProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OMDBProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OMDBProject.styles.css" asp-append-version="true" />
</head>
<body style="background-color:darkgray" >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OMDBProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a style = "color:#f5c518" class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a style = "color:#f5c518" class="nav-link " asp-area="" asp-controller="IMDB" asp-action="MovieSearch">Movie Search</a>
                        </li>
                        <li class="nav-item">
                            <a style = "color:#f5c518" class="nav-link " asp-area="" asp-controller="IMDB" asp-action="MovieNight">Movie Night</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OMDBProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>